version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: sched-u-app
    container_name: sched-u-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - DB_HOST=db
      - DB_DATABASE=schedU
      - DB_USERNAME=admin
      - DB_PASSWORD=root@123
    networks:
      - sched-u-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: sched-u-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: schedU
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - sched-u-network

volumes:
  dbdata:

networks:
  sched-u-network:
    driver: bridge
